# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Valerio Cestarelli's University Projects

description: Portfolio
author:
  name: Valerio Cestarelli
  email: v.cestarelli@gmail.com
  github: v1ll0
  twitter: MassimoX90
  linkedin: valeriocestarelli

categories_path: categories.html
tags_path: tags.html

BASE_PATH:

theme: jekyll-theme-slate